// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TheWayToGerman.Core.Database;

#nullable disable

namespace TheWayToGerman.Core.Migrations
{
    [DbContext(typeof(PostgresDBContext))]
    partial class PostgresDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TheWayToGerman.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserType")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4413e488-a54e-43df-b381-f48fc81b7080"),
                            CreateDate = new DateTime(2023, 5, 9, 10, 20, 10, 290, DateTimeKind.Utc).AddTicks(7685),
                            Email = "masaylighto@gmail.com",
                            Name = "mohammed",
                            Password = "CPDk5fucxtvODK+MF0+aTUYOuKMtNki1m2dFSz8gbioATBjHPIk+IDMUkSeJKiQCIXOV9quaCwL0sAu5aYfrGA==",
                            UpdateDate = new DateTime(2023, 5, 9, 10, 20, 10, 290, DateTimeKind.Utc).AddTicks(7686),
                            UserType = 1,
                            Username = "masaylighto"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
