name: Deploy to Amazon ECS
on:
  push:
    branches:
      - master
      - develop
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
          
      - name: Build
        run: dotnet build TheWayToGerman.sln
        
      - name: Test
        run: dotnet test TheWayToGerman.sln
  deploy:
    name: deploy
    needs: build
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
          
      - name: Deploy code to EC2 instance
        run: |
         ls
         echo ${{ secrets.EC2_SSH_KEY }} >> ../key.pem 
         ls ../
         sudo chmod 600 ../key.pem 
         ls ~/${{ secrets.Target }}/
         rsync -v -Pav -e "ssh -i ../key.pem" . ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:~/${{ secrets.Target }}/
         ssh -i "../key.pem"  ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}  "cd ~/${{ secrets.Target }}/ ; sudo docker-compose -p "the_way_to_german_api" up --build -d ;  dotnet clean TheWayToGerman.sln"
         sudo rm  ../key.pem 
         
