name: Deploy to Amazon ECS
on:
  push:
    branches:
      - master
      - develop
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
          
      - name: Build
        run: dotnet build TheWayToGerman.sln
        
      - name: Test
        run: dotnet test TheWayToGerman.sln
        
      - name: Deploy code to EC2 instance
        uses: easingthemes/ssh-deploy@v4.1.8
        with:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: ./
          REMOTE_HOST: ${{ secrets.EC2_HOST }}
          REMOTE_USER: ${{ secrets.EC2_USERNAME }}
          EXCLUDE: "Diagram/"
          TARGET: ${{ secrets.Target }}
          SCRIPT_AFTER: |
            cd TheWayToGermanApi
            sudo docker-compose -p "the_way_to_german_api" up --build
