name: Deploy to Amazon ECS

on:
  push:
    branches: [ "master" ,"develop"]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Deploy code to EC2 instance
      uses: easingthemes/ssh-deploy@v2.1.5
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
        source: ./
        server: ${{ secrets.EC2_SERVER }}
        username: ${{ secrets.EC2_USERNAME }}
        destination: ~/TheWayToGermanApi
        commands: |
          ls -al
          docker-compose up
            
